# Generated by Django 3.0.6 on 2020-06-12 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chartName', models.CharField(blank=True, default='chart', max_length=60)),
                ('chartType', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='OverallFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overallfigurename', models.CharField(max_length=60)),
                ('pythoncode', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='StockFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockfigureValue', models.FloatField(max_length=60)),
                ('stockmainfigure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.OverallFigure')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tickersymbol', models.CharField(max_length=60)),
                ('stock_figure', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.StockFigure')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figureValue', models.FloatField(default=1.0, max_length=60)),
                ('portfoliomainfigure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.OverallFigure')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioname', models.CharField(max_length=60)),
                ('fundmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('portfolio_figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.PortfolioFigure')),
                ('stock', models.ManyToManyField(to='PortfolioScreen.Stock')),
            ],
        ),
    ]
