# Generated by Django 3.0.6 on 2020-05-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chartName',
            field=models.CharField(blank=True, default='chart23', max_length=60),
        ),
    ]
