# Generated by Django 3.0.6 on 2020-06-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_figure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.PortfolioFigure'),
        ),
    ]
