# Generated by Django 3.0.6 on 2020-05-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliofigure',
            name='figurename',
            field=models.CharField(default='beta', max_length=60),
        ),
    ]
