# Generated by Django 3.0.6 on 2020-05-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0002_auto_20200524_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chartName',
            field=models.CharField(blank=True, default='chart', max_length=60),
        ),
    ]
