# Generated by Django 3.0.6 on 2020-06-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0002_auto_20200612_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_figure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.PortfolioFigure'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_figure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.StockFigure'),
        ),
    ]
