# Generated by Django 3.0.6 on 2020-06-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0003_auto_20200612_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_figure',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_figure',
            field=models.ManyToManyField(to='PortfolioScreen.StockFigure'),
        ),
    ]
