# Generated by Django 3.0.6 on 2020-06-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0004_auto_20200612_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overallfigure',
            old_name='overallfigurename',
            new_name='name',
        ),
    ]
