# Generated by Django 3.0.6 on 2020-06-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0005_auto_20200612_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofigure',
            name='portfoliomainfigure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.OverallFigure'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_figure',
            field=models.ManyToManyField(null=True, to='PortfolioScreen.StockFigure'),
        ),
        migrations.AlterField(
            model_name='stockfigure',
            name='stockmainfigure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.OverallFigure'),
        ),
    ]
