# Generated by Django 3.0.6 on 2020-06-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0006_auto_20200612_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_figure',
            field=models.ManyToManyField(to='PortfolioScreen.StockFigure'),
        ),
    ]
