# Generated by Django 3.0.6 on 2020-06-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0007_auto_20200612_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_figure',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_figure',
            field=models.ManyToManyField(to='PortfolioScreen.PortfolioFigure'),
        ),
    ]
