# Generated by Django 3.0.6 on 2020-06-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0008_auto_20200612_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliofigure',
            old_name='portfoliomainfigure',
            new_name='overallfigure',
        ),
        migrations.RenameField(
            model_name='stockfigure',
            old_name='stockmainfigure',
            new_name='overallfigure',
        ),
    ]
