# Generated by Django 3.0.6 on 2020-06-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0009_auto_20200612_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Tickersymbol',
            new_name='tickersymbol',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_figure',
        ),
        migrations.AddField(
            model_name='stockfigure',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.Portfolio'),
        ),
        migrations.AddField(
            model_name='stockfigure',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.Stock'),
        ),
    ]
