# Generated by Django 3.0.6 on 2020-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0010_auto_20200625_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.CharField(default='', max_length=60, null=True),
        ),
    ]
