# Generated by Django 3.0.6 on 2020-06-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0011_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioFigureHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figures', models.ManyToManyField(to='PortfolioScreen.OverallFigure')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PortfolioScreen.Portfolio')),
            ],
        ),
    ]
