# Generated by Django 3.0.6 on 2020-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0012_portfoliofigureheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fullname',
            field=models.CharField(default='', max_length=60, null=True),
        ),
    ]
