# Generated by Django 3.0.6 on 2020-07-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0013_stock_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfigure',
            name='stockfigureValue',
            field=models.CharField(max_length=60),
        ),
    ]
