# Generated by Django 3.0.6 on 2020-07-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioScreen', '0014_auto_20200701_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallfigure',
            name='pythoncode',
            field=models.TextField(max_length=8000),
        ),
    ]
