pipenv shell
pip install urllib3
pip install six
pip install botocore
pip install boto3
pip install s3transfer
pip install awscli
pip install python-dateutil
pip install requests
pip install S3transfer
pip install Certifi
pip install Idna
pip install PyYAML
pip install Pyasn1
pip install Docutils
pip install Chardet
pip install RSA
pip install Jmespath
pip install setuptools
pip install awscli
pip install Pytz
pip install futures
pip install colorama
pip install Simplejson
pip install Boto3
pip install Pytest
pip install NumPy
pip install pandas
pip install SciPy
pip install Finance-Python
pip install pandas-finance
pip install yfinance
pip install Financial
pip install Tornado
pip install pyramid
pip install flask
pip install csvtool
pip install csvkit
pip install pdftools
pip install pdf-tools
pip install pikepdf
